- hosts: myremote
  tasks:
    - debug:
        msg: "currently using os is: {{ansible_distribution}}, {{ansible_hostname}}"
      delegate_to: 127.0.0.1
    - debug:
        msg: "currently using os is: {{ansible_distribution}}, {{ansible_hostname}}"
